[project]
name = "mcp-client-monitoring"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.69.0",
    "google-genai>=1.43.0",
    "mcp>=1.17.0",
    "python-dotenv>=1.1.1",
]
